version: '3.8'

services:
  uspray-spring:
    image: registry.uspray.kr/uspray-server-dev:latest
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8080"
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN_HOST}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080"

  redis:
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server

volumes:
  redis_data: