version: '3.8'

services:
  uspray-spring:
    image: registry.uspray.kr/uspray-server-dev:latest
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8002:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server

volumes:
  redis_data: