version: '3.8'

services:
  uspray-spring:
    image: bae4614/uspray-server:latest
    container_name: prayhelper-spring-dev
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8002:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server

volumes:
  redis_data: